function [fitresult, gof] = createFit(La, OT)
%CREATEFIT(LA,OT)
%  Create a fit.
%
%  Data for 'Lat vs OT' fit:
%      X Input : La
%      Y Output: OT
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 14-Feb-2021 08:25:05


%% Fit: 'Lat vs OT'.
[xData, yData] = prepareCurveData( La, OT );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, 'Normalize', 'on' );

% Plot fit with data.
figure( 'Name', 'Latitude vs Optimal Tilt' );
h = plot( fitresult, xData, yData);
legend( h,'Latitude vs Optimal Tilt', 'Line Of Best Fit', 'Location', 'NorthEast' );
% Label axes
xlabel('Latitude (°)')
ylabel('Optimal Tilt (°)')
grid on


