function [fitresult, gof] = createFit1(Months, Tilt_Angles, Optimal_Tilt)
%CREATEFIT1(MONTHS,TILT_ANGLES)
%  Create a fit.
%
%  Data for 'Karachi' fit:
%      X Input : Months
%      Y Output: Tilt_Angles
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 03-Jan-2021 07:41:27


%% Fit: 'Karachi'.
[xData, yData] = prepareCurveData( Months, Tilt_Angles );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = 0.99999999999999;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Karachi' );
h = plot( fitresult, xData, yData );
h(1).MarkerSize = 15;
legend( h, 'Tilt Angles vs. Months', 'Optimum Tilt Angles', 'Location', 'North' );
% Label axes
xlabel('Months')
ylabel('Tilt Angles (Degrees)')
xlim([1 12])
title('Monthly Optimal Tilt Angle')
grid on
hold on 
plot(Months,Optimal_Tilt*ones(size(Months)), 'LineStyle','--' , 'DisplayName','Fixed Optimal Tilt')
end
